---
# tasks file for start_stop_ec2

- name: Get instance details
  include: get_instance_details.yml

- name: Start instances
  include: start/start_instances.yml
  when: action == "start"

- name: Stop instances
  include: stop/stop_instances.yml
  when: action == "stop"