
- debug: var="{{instances_details.instances|map(attribute='id')|list|unique}}"

- name: Start instances
  ec2:
    instance_id: "{{item}}"
    state: running
  with_items: "{{instances_details.instances|map(attribute='id')|list|unique}}"